### ISSUE TITLE
use `|` instead of `or` for type annotations, `or` is wrong

### ISSUE THREAD

**Issue by mahdihaghverdi** [ManiMozaffar/edd-exchange#2]
https://github.com/ManiMozaffar/edd-exchange/blob/27032e7d92e6ff35d79b3d83e783cc95f637a4c4/shared/shared/entities/money.py#L36

if you look at `__init__.__annotations__` it is evaluated as: `{'amount': <class 'float'>}` which is wrong

**Comment by ManiMozaffar** [comment]
Hmm that's weird I alway use "|".
